### ISSUE TITLE
AnimatePresence - Issues with exit

### ISSUE THREAD

**Issue by Hirbod** [nandorojo/moti#104]
Hi @nandorojo

maybe it's because I didn't understand it correctly, but I was hoping that I can also trigger the exit animation when I re-render a component.

```ts
const TextContainer = ({ index }: { index: number }) => {
  return (
    <AnimatePresence>
      <MotiView
        from={{
          opacity: 0,
          scale: 0.9,
          translateY: 30,
        }}
        animate={{
          opacity: 1,
          scale: 1,
          translateY: 0,
        }}
        exit={{
          opacity: 0,
          scale: 0.9,
        }}
        style={styles.textContainer}
        transition={{ type: "timing", duration: 400, delay: 50 }}
      >
        <Text style={styles.title}>{bottles[index].name}</Text>
        <Text style={styles.subtitle}>{bottles[index].slogan}</Text>
      </MotiView>
    </AnimatePresence>
  );
};

```

I have created a functional component which contains AnimatePresence and a MotiView.

I call the component itself like this inside my Screen.
```ts
<TextContainer key={index) />
```

I only pass the index so that the component re-renders (forcing a re-render when user picks a different bottle). The index change will update the Text inside `TextContainer`.

The animations works perfectly, but the `exit` animation does not happen. Looks like react just remove the element and renders it once again. Maybe I did not understand the concept of exit animations correctly, but I thought, a re-render is a unmount + mount.

**Comment by nandorojo** [comment]
Pass a unique key to `MotiView` if you want it to trigger exit animations when the `key` changes. And maybe pass `exitBeforeEnter` to `AnimatePresence`

**Comment by nandorojo** [comment]
So in your case, `key={index}`

**Comment by Hirbod** [comment]
```
const TextContainer = ({ index }: { index: number }) => {
  return (
    <AnimatePresence exitBeforeEnter>
      <MotiView
        key={index}
        from={{
          opacity: 0,
          scale: 0.9,
          translateY: 30,
        }}
        animate={{
          opacity: 1,
          scale: 1,
          translateY: 0,
        }}
        exit={{
          opacity: 0,
          scale: 0.9,
        }}
        style={styles.textContainer}
        transition={{ type: "timing", duration: 400, delay: 50 }}
      >
        <Text style={styles.title}>Rémy Martin {bottles[index].name}</Text>
        <Text style={styles.subtitle}>{bottles[index].slogan}</Text>
      </MotiView>
    </AnimatePresence>
  );
};
```

Not working unfortunately.

**Comment by Hirbod** [comment]
Ok, so the main reason was, that I was actually passing `key` to `TextContainer`. I changed `key` to `motiKey` and added `key={motiKey}` to MotiView. It does play the exitAnimation now, but since it is the same element, it stays invisible after the exit. If I remove `exitBeforeEnter`, the exit and animate work, but it elements position is messed up.

Here is a little GIF demonstrating the issue @nandorojo 
https://streamable.com/njn7g4

**Comment by nandorojo** [comment]
> It does play the exitAnimation now, but since it is the same element, it stays invisible after the exit.

I don't see how that would happen if you're using key properly. Can you make a basic snack?

**Comment by nandorojo** [comment]
Oh man, I think this might be another regression from 0.11. Does downgrading fix it?

**Comment by Hirbod** [comment]
Well your examples have a condition (like the examples with `visible`), mine not. 
I use the same component. But as you can see in my video, it does somehow work with `exitBeforeEnter`, but it does not free the space. Kinda only works when I use position absolute.

I will try a downgrade now.

**Comment by Hirbod** [comment]
WORKS PERFECTLY with 0.11... haha

**Comment by Hirbod** [comment]
So it's not me :D

**Comment by nandorojo** [comment]
🤦‍♂️

**Comment by Hirbod** [comment]
I can tell for sure, that with 0.11, it does work with `exitBeforeEnter` as desired and without it does also work but it jumps (which is correct though, since two elements get rendered at the same time).

0.12 has a regression and breaks.

**Comment by nandorojo** [comment]
yeah...oh man. looking into this lol

**Comment by Hirbod** [comment]
I am known at my partners and freelancers to find every bug they try to hide :D

**Comment by nandorojo** [comment]
I happened to see the same issue in our app at the same time.

**Comment by Hirbod** [comment]
Here is how it looks like with 0.11
https://streamable.com/0ywu6m

**Comment by nandorojo** [comment]
I'm seeing just an empty render for all non-initial renders after the first exit. Maybe the exit isn't triggering. Will report back.

**Comment by nandorojo** [comment]
Yeah, I fixed it. Went overboard on a memoization. Will push now.

**Comment by nandorojo** [comment]
Published in `0.12.2`, could you try that?

**Comment by Hirbod** [comment]
Fixed! You earned yourself a sponsoring!

**Comment by nandorojo** [comment]
I'm still facing some issues with this release myself with animate presence. looking into it more.

**Comment by nandorojo** [comment]
Yeah, only on iOS. Investigating further.

**Comment by Hirbod** [comment]
Ok, I just tested on Web so far.

**Comment by nandorojo** [comment]
It seems that the solution I used for native, which wraps `from`, `animate`, and `exit` with `useDerivedValue`, is causing the values to show as `undefined` inside of `useAnimatedStyle`. Basically, if I remove the order of `transforms`, fix, then everything gets solved. Seems like a fundamental Reanimated 2 bug. I might have to revert back.

**Comment by nandorojo** [comment]
I think this issue has to get fixed in order for moti to not be messed up when there are multiple `transform` properties. https://github.com/software-mansion/react-native-reanimated/issues/2352

**Comment by nandorojo** [comment]
I'll try that, but I believe the order of keys gets reversed randomly (as shown on that issue)

**Comment by Hirbod** [comment]
The iteration order for objects follows a certain set of rules since ES2015, but it does not guarantee  to follow the insertion order. I think that JSI might work differently here and does not respect own property order. 

Map shares some similarities with Object and guarantees the keys to be iterated in order of insertion, without exception.
But since I really don't know how REA2 works internally, I am not sure if using a Map is even possible.

**Comment by nandorojo** [comment]
I'm revering back as this caused a harsh regression. The only solution is likely to use a `transform` array.

**Comment by nandorojo** [comment]
Re-opened https://github.com/nandorojo/moti/issues/76

and added context on the aforementioned Reanimated issue. It's a bummer that object key order isn't preserved – I really like the current API.

**Comment by nandorojo** [comment]
I also now see why it works with `useAnimatedStyle`: we're always updating shared values directly, as opposed to passing JS objects into worklets.

**Comment by nandorojo** [comment]
Opened a PR here, this is working well: https://github.com/nandorojo/moti/pull/105

**Comment by Hirbod** [comment]
Is the old api for single attributes (translateY: -20) still working or is it a breaking change?

**Comment by nandorojo** [comment]
It’s not a breaking change. The old API works still, but the docs won’t recommend it for multiple transforms.

**Comment by nandorojo** [comment]
I added docs explaining this. I also added a warning inside of components. If you use multiple inline transforms, it'll tell you to change to an array.

**Comment by nandorojo** [comment]
Published in `0.13.0`
