### ISSUE TITLE
Android emulator MotiPressable doesn't trigger

### ISSUE THREAD

**Issue by ppkinev** [nandorojo/moti#143]
Hey, there. I could be doing something wrong there as just started to use Moti, but here's an issue I have:

Super simple example:
```js
import { MotiPressable } from 'moti/interactions'

export const TestScreen = () => {
  const [counter, setCounter] = useState(0)
  const increase = () => setCounter(value => value + 1)

  return (
    <View>
      <MotiPressable 
        onPress={increase}
        accessibilityRole="button"
      >
        <Text>Value: {counter}</Text>
      </MotiPressable>
    </View>
  )
}
```
It works on ios, simulator, web but not android, while this one works fine everywhere (though no moti anymore):

```js
import { Pressable } from 'react-native'

export const TestScreen = () => {
  const [counter, setCounter] = useState(0)
  const increase = () => setCounter(value => value + 1)

  return (
    <View>
      <Pressable 
        onPress={increase}
        accessibilityRole="button"
      >
        <Text>Value: {counter}</Text>
      </Pressable>
    </View>
  )
}
```

By not working I mean, no clicks happen, android completely ignores clicking on this component. Used Android 11 with API 30 emulator.

Is there something I might be missing?

**Comment by nandorojo** [comment]
Hmm this may be an issue with the gesture handler on Android. Did you wrap your app with the gesture handler root view?

**Comment by ppkinev** [comment]
@nandorojo you are so right. I feel embarrassed now as everything worked in web/ios without wrapping app in `gesture handler`, android apparently needs it. Thanks for a quick reply, the problem is now solved.

**Comment by Hmoulvad** [comment]
I am still seeing this issue on Android and I've already tried the fix with wrapping the App in `GestureHandlerRootView`. Any suggestions. It works flawlessly on IOS.

**Comment by nandorojo** [comment]
on the latest moti version?

**Comment by Hmoulvad** [comment]
> on the latest moti version?

Yes in 0.18.0 version.

**Comment by nandorojo** [comment]
does it work on expo snack? that’s really odd. can i see your code?

**Comment by nandorojo** [comment]
can you run `yarn why moti`

**Comment by Hmoulvad** [comment]
I am not using Expo. 

`yarn why moti
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "moti"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "moti@0.17.1"
info Has been hoisted to "moti"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "464KB"
info Disk size with unique dependencies: "1.1MB"
info Disk size with transitive dependencies: "7.86MB"
info Number of shared dependencies: 3
`
