### ISSUE TITLE
type error when using transition prop with expo 51 and reanimted 3.10

### ISSUE THREAD

**Issue by dannyhw** [nandorojo/moti#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

Type '{ duration: number; }' is not assignable to type 'MotiTransitionProp<StyleValueWithReplacedTransforms<ViewStyle | TextStyle | ImageStyle>> | ((custom?: any) => MotiTransition<...>) | undefined'.

Type '{ type: "timing"; duration: number; }' is not assignable to type 'MotiTransitionProp<StyleValueWithReplacedTransforms<ViewStyle | TextStyle | ImageStyle>> | undefined'.

Type '{ type: "timing"; duration: number; delay: number; }' is not assignable to type 'MotiTransitionProp<StyleValueWithReplacedTransforms<ViewStyle | TextStyle | ImageStyle>> | undefined'.

### Steps To Reproduce

Heres some examples that give me a type error 

   ```
   <MotiView
                from={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                // @ts-ignore TODO moti fix me
                transition={{
                  type: "timing",
                  duration: 1000,
                  delay: index * 1000,
                }}
              >
     <MotiView
          tw="w-full items-center"
          from={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          // @ts-ignore TODO moti fix me
          transition={{
            type: "timing",
            duration: 1000,
          }}
        >
         <View
            from={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{
              opacity: 0,
            }}
            // @ts-ignore TODO moti fix me
            exitTransition={{ duration: 300 }}
          >
          <View
            from={{ translateY: 128 + 64 + 8, opacity: 0 }}
            animate={{ translateY: 0, opacity: 1 }}
            exit={{
              translateY: 128 + 64 + 8,
              opacity: 0,
            }}
            // @ts-ignore TODO moti fix me
            exitTransition={{ duration: 300 }}
          >
 ```

### Versions

```markdown
- Moti: ^0.28.1
- Reanimated: ~3.10.1
- React Native: 0.74.1
- typescript: ^5.3.3
```

### Screenshots

![image](https://github.com/nandorojo/moti/assets/3481514/1894f5d8-d97a-451f-a690-60cc69105bfa)

### Reproduction

https://github.com/dannyhw/moti-types-repro

Run

```
bun install
bun check
```

**Comment by ThatGuySam** [comment]
Getting the same issue when trying to get ahead of migration to Expo 51

"moti": "^0.28.1",
"react-native-reanimated": "~3.10.1",

**Comment by dannyhw** [comment]
I'm able to get around the issue by changing to

``` 
transition={{
    opacity: {
      type: "timing",
      duration: 1000,
   }
}}
```

But its a bit tedious with multiple properties

**Comment by nandorojo** [comment]
Fixed https://github.com/nandorojo/moti/pull/345

**Comment by nandorojo** [comment]
Releasing shortly

**Comment by agallio** [comment]
I'm using version 0.29.0 with Expo SDK 51 and still get the issue. 

<img width="229" alt="image" src="https://github.com/nandorojo/moti/assets/22767465/c5e2550d-2509-4664-a0c4-60f66eefb816">

**Comment by nandorojo** [comment]
@alantoa looks like some people are still getting this on SDK 51, interesting

**Comment by alantoa** [comment]
Hey @agallio, actually it works for me.
What if you run `yarn why moti` and `yarn why react-native-reanimated` in your project? 
Curious about the version you are actually using. 

![CleanShot 2024-05-15 at 23 01 06@2x](https://github.com/nandorojo/moti/assets/37520667/47c24ebe-3c56-4c50-8b82-24e661be13d5)

**Comment by alantoa** [comment]
Also, Can you please show me the type error in your code? (Hover over the error and take a screenshot of the error text.) @agallio

**Comment by agallio** [comment]
Hi @alantoa, thank you for the response. It's working now, I think it was because of my faulty `node_modules`, when I tried to wipe all the `node_modules` and `yarn.lock` and then reinstall, it worked properly.

**Comment by alantoa** [comment]
Got it, that's great!

**Comment by RazaShehryar** [comment]
Facing this issue with expo SDK 50. 

moti version 0.29
react-native-reanimated version 3.6.2

**Comment by nandorojo** [comment]
You'll need to upgrade RN. The type issue is due to a typo in a react native type. The typo was fixed in RN 0.74

**Comment by thoth-seshat** [comment]
@nandorojo I'm using RN 0.74.3 and still see this issue

**Comment by nandorojo** [comment]
please make sure you don't have types/react-native installed

**Comment by thoth-seshat** [comment]
@nandorojo I've uninstalled `types/react-native`, restarted TS and still see the issue

**Comment by MarcHbb** [comment]
I have the same issue.

```
"expo": "~51.0.22",
"react-native": "0.74.3",
"moti": "0.28"
 ```

**Comment by markmccoid** [comment]
You need moti v0.29.

Try 

`npm install moti@latest`

**Comment by MarcHbb** [comment]
@markmccoid Still have the error, event with restarting ts server

**Comment by dav1rm** [comment]
Same issue here.
```
"react-native": "0.73.6",
"moti": "^0.29.0",
"react-native-reanimated": "^3.12.1"
```
![image](https://github.com/user-attachments/assets/0d05a93f-672a-444a-92ea-9cc5f7b74755)

**Comment by nandorojo** [comment]
Will check on a fix soon, thanks for reporting

**Comment by nandorojo** [comment]
I think it’s actually due to how newer TS versions resolve declaration file `import()` statements. I fixed something similar in Zeego which wrapped radix.

**Comment by Geeknerd1337** [comment]
Also getting this issue

**Comment by bryanmylee** [comment]
This issue occurs due to the type intersection that's being created over multiple definitions of the `transition` prop.

I'm getting this issue when using `motify` on a Tamagui `View` component as well, since it exposes a `transition: "allow-discrete"` prop.

I'm sure this will be an issue with other libraries as well. My suggestion would be to explicitly specify the prop type as `MotiProps & Omit<OriginalProps, keyof MotiProps>` to indicate that Moti will take over these props.

**Comment by bryanmylee** [comment]
A patch to this function would work:

```tsx
const Motified = forwardRef<
      Ref,
//      Props &
      Omit<Props, keyof MotiProps> &
        AnimatedProps<Props> &
        MotiProps<Animate> & {
          children?: React.ReactNode
        }
    >(
```

**Comment by bryanmylee** [comment]
For people who want a quick fix, add this to your codebase somewhere.

```ts
declare module "moti" {
  function motify<
    Props extends object,
    Ref,
    Animate = ViewStyle | ImageStyle | TextStyle,
  >(
    ComponentWithoutAnimation: React.ComponentType<Props>,
  ): () => React.ForwardRefExoticComponent<
    Omit<Props, keyof MotiProps<Animate>> &
      AnimatedProps<Props> &
      MotiProps<Animate> & {
        children?: React.ReactNode;
      } & React.RefAttributes<Ref>
  >;
}
```
