### ISSUE TITLE
Expo SDK 53 library error for web app

### ISSUE THREAD

**Issue by pjadczak** [nandorojo/moti#380]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Do you want this issue prioritized?

- [x] Yes, I have sponsored
- [x] Not urgent

### Current Behavior

Cannot use moti components in web application for Expo SDK 53, I get an error on the screen:

Cannot destructure property '__extends' of '_tslib.default' as it is undefined.

### Expected Behavior

Launching the Expo 53 web app

### Steps To Reproduce

Run web app.

### Versions

```markdown
- Moti: 0.20.0
- Reanimated: 3.17.4
- React Native: 0.79.3
```

### Screenshots

![Image](https://github.com/user-attachments/assets/a3cb83d7-317c-40be-8ebd-a48790e8e4f6)

### Reproduction

npx create-expo-app@latest TestApp
cd TestApp
npm run start (and press "w" to start web app)

place in app <MotiView /> or other Moti component and try run.

**Comment by Zloka** [comment]
I just opened #381 which may be helpful.

Make sure you are using `sourceExts` and not `assetExts` like in the code sample - I got similar, cryptic stacktraces until I corrected that.

**Comment by pjadczak** [comment]
I was using a configuration file to handle svg files (width sourceExts and assetExts), I deleted this file (metro.config.js), but it didn't help, I still have the same problem with this error message.

**Comment by tjhannes** [comment]
This helped for me: https://community.apollographql.com/t/cannot-destructure-property-extends-of-tslib-default-as-it-is-undefined/9501/2
